// <auto-generated />
using System;
using AutoPartsPOS.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoPartsPOS.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618204723_AddWeightedAverageCost")]
    partial class AddWeightedAverageCost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("AutoPartsPOS.Domain.Catalog.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("barcode");

                    b.Property<long>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<decimal>("CurrentAverageCost")
                        .HasPrecision(14, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("current_average_cost");

                    b.Property<decimal>("CurrentStock")
                        .HasPrecision(14, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("current_stock");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("MinimumStock")
                        .HasPrecision(14, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("minimum_stock");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("name_ar");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("product_code");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("purchase_price");

                    b.Property<decimal>("SellingPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("selling_price");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("ux_products_barcode")
                        .HasFilter("barcode IS NOT NULL");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_products_is_active");

                    b.HasIndex("NameAr")
                        .HasDatabaseName("ix_products_name_ar");

                    b.HasIndex("ProductCode")
                        .IsUnique()
                        .HasDatabaseName("ux_products_product_code");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_current_average_cost_non_negative", "current_average_cost >= 0");

                            t.HasCheckConstraint("ck_products_current_stock_non_negative", "current_stock >= 0");

                            t.HasCheckConstraint("ck_products_minimum_stock_non_negative", "minimum_stock >= 0");

                            t.HasCheckConstraint("ck_products_purchase_price_non_negative", "purchase_price >= 0");

                            t.HasCheckConstraint("ck_products_selling_price_non_negative", "selling_price >= 0");
                        });
                });

            modelBuilder.Entity("AutoPartsPOS.Domain.Catalog.ProductCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("name_ar");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_product_categories_is_active");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasDatabaseName("ux_product_categories_name_ar");

                    b.ToTable("product_categories", (string)null);
                });

            modelBuilder.Entity("AutoPartsPOS.Domain.Inventory.InventoryTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(14, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("balance_after");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(14, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.Property<long>("ReferenceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("reference_type");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_date");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_inventory_transactions_product_id");

                    b.HasIndex("TransactionDate")
                        .HasDatabaseName("ix_inventory_transactions_transaction_date");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("ix_inventory_transactions_reference");

                    b.ToTable("inventory_transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_transactions_balance_after_non_negative", "balance_after >= 0");

                            t.HasCheckConstraint("ck_inventory_transactions_quantity_not_zero", "quantity <> 0");

                            t.HasCheckConstraint("ck_inventory_transactions_reference_type", "reference_type IN ('PurchaseInvoice', 'SalesInvoice', 'ManualAdjustment')");

                            t.HasCheckConstraint("ck_inventory_transactions_transaction_type", "transaction_type IN ('Purchase', 'Sale', 'Adjustment', 'VoidPurchase', 'VoidSale')");
                        });
                });

            modelBuilder.Entity("AutoPartsPOS.Domain.Purchases.PurchaseInvoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_number");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("SupplierId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supplier_id");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("total_amount");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<string>("VoidReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("void_reason");

                    b.Property<DateTimeOffset?>("VoidedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("voided_at");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceDate")
                        .HasDatabaseName("ix_purchase_invoices_invoice_date");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_purchase_invoices_invoice_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_purchase_invoices_status");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_purchase_invoices_supplier_id");

                    b.ToTable("purchase_invoices", null, t =>
                        {
                            t.HasCheckConstraint("ck_purchase_invoices_status", "status IN ('Posted', 'Voided')");

                            t.HasCheckConstraint("ck_purchase_invoices_total_non_negative", "total_amount >= 0");
                        });
                });

            modelBuilder.Entity("AutoPartsPOS.Domain.Purchases.PurchaseInvoiceItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<long>("PurchaseInvoiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("purchase_invoice_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(14, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("total_price");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_purchase_invoice_items_product_id");

                    b.HasIndex("PurchaseInvoiceId")
                        .HasDatabaseName("ix_purchase_invoice_items_purchase_invoice_id");

                    b.ToTable("purchase_invoice_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_purchase_invoice_items_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_purchase_invoice_items_total_price_non_negative", "total_price >= 0");

                            t.HasCheckConstraint("ck_purchase_invoice_items_unit_price_non_negative", "unit_price >= 0");
                        });
                });

            modelBuilder.Entity("AutoPartsPOS.Domain.Sales.SalesInvoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("discount_amount");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_number");

                    b.Property<decimal>("NetTotalAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("net_total_amount");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<decimal>("SubtotalAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("subtotal_amount");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<string>("VoidReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("void_reason");

                    b.Property<DateTimeOffset?>("VoidedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("voided_at");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceDate")
                        .HasDatabaseName("ix_sales_invoices_invoice_date");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_sales_invoices_invoice_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_sales_invoices_status");

                    b.ToTable("sales_invoices", null, t =>
                        {
                            t.HasCheckConstraint("ck_sales_invoices_amounts_non_negative", "subtotal_amount >= 0 AND discount_amount >= 0 AND net_total_amount >= 0");

                            t.HasCheckConstraint("ck_sales_invoices_net_total_valid", "net_total_amount = subtotal_amount - discount_amount");

                            t.HasCheckConstraint("ck_sales_invoices_status", "status IN ('Posted', 'Voided')");
                        });
                });

            modelBuilder.Entity("AutoPartsPOS.Domain.Sales.SalesInvoiceItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(14, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.Property<long>("SalesInvoiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sales_invoice_id");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("total_cost");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("total_price");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(14, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_cost");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_sales_invoice_items_product_id");

                    b.HasIndex("SalesInvoiceId")
                        .HasDatabaseName("ix_sales_invoice_items_sales_invoice_id");

                    b.ToTable("sales_invoice_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_sales_invoice_items_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_sales_invoice_items_total_cost_non_negative", "total_cost >= 0");

                            t.HasCheckConstraint("ck_sales_invoice_items_total_price_non_negative", "total_price >= 0");

                            t.HasCheckConstraint("ck_sales_invoice_items_unit_cost_non_negative", "unit_cost >= 0");

                            t.HasCheckConstraint("ck_sales_invoice_items_unit_price_non_negative", "unit_price >= 0");
                        });
                });

            modelBuilder.Entity("AutoPartsPOS.Domain.Settings.AppSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("setting_key");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("setting_value");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("AutoPartsPOS.Domain.Suppliers.Supplier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name_ar");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_suppliers_is_active");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasDatabaseName("ux_suppliers_name_ar");

                    b.HasIndex("Phone")
                        .HasDatabaseName("ix_suppliers_phone");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("AutoPartsPOS.Domain.Catalog.Product", b =>
                {
                    b.HasOne("AutoPartsPOS.Domain.Catalog.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AutoPartsPOS.Domain.Inventory.InventoryTransaction", b =>
                {
                    b.HasOne("AutoPartsPOS.Domain.Catalog.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AutoPartsPOS.Domain.Purchases.PurchaseInvoice", b =>
                {
                    b.HasOne("AutoPartsPOS.Domain.Suppliers.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("AutoPartsPOS.Domain.Purchases.PurchaseInvoiceItem", b =>
                {
                    b.HasOne("AutoPartsPOS.Domain.Catalog.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoPartsPOS.Domain.Purchases.PurchaseInvoice", "PurchaseInvoice")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseInvoice");
                });

            modelBuilder.Entity("AutoPartsPOS.Domain.Sales.SalesInvoiceItem", b =>
                {
                    b.HasOne("AutoPartsPOS.Domain.Catalog.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoPartsPOS.Domain.Sales.SalesInvoice", "SalesInvoice")
                        .WithMany("Items")
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SalesInvoice");
                });

            modelBuilder.Entity("AutoPartsPOS.Domain.Catalog.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AutoPartsPOS.Domain.Purchases.PurchaseInvoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AutoPartsPOS.Domain.Sales.SalesInvoice", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
